### ISSUE TITLE
Permalink for single sites that change song content?

### ISSUE THREAD

**Issue by jphastings** [toby/playgrub#16]
For music sites that have a constant URL but who's content change (eg. http://www.apple.com/itunes/charts/songs/) it'd be great to have a special xspf URL on playgrub that will always be the most recent playlist generated from that site.

The playlists could work as they do now, but when someone grubs any one of a specified group of sites (like the apple charts) the url http://playgrub.com/applechart.xspf could be updated to point to the most recent xspf generated from the relevant site.

**Comment by toby** [comment]
implemented, see here: http://playgrub.posterous.com/latest-xspf-links
